# Generated by Django 6.0.6 on 2026-06-17 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fantasia', models.CharField(max_length=150)),
                ('cuit', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('provincia', models.CharField(default='Córdoba', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_consultoras/')),
                ('color_primario', models.CharField(default='#1A446C', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformeVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento_ocasional', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('observaciones_generales', models.TextField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chaleco_app.clienteempresa')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaleco_app.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='HallazgoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_planta', models.CharField(max_length=100)),
                ('descripcion_desvio', models.TextField()),
                ('es_condicion_insegura', models.BooleanField(default=True)),
                ('foto_evidencia', models.ImageField(upload_to='hallazgos_fotos/')),
                ('medida_correctiva_sugerida', models.TextField()),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='chaleco_app.informevisita')),
            ],
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaleco_app.organizacion'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_administrador', models.BooleanField(default=False)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaleco_app.organizacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
