# Generated by Django 6.0.6 on 2026-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteempresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clienteempresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
