# Generated by Django 6.0.6 on 2026-07-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleco_app', '0002_clienteempresa_activo_clienteempresa_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgoriesgo',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('En Progreso', 'En Progreso'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20),
        ),
        migrations.AddField(
            model_name='hallazgoriesgo',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallazgoriesgo',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='hallazgos_fotos/'),
        ),
    ]
