# Generated by Django 6.0.6 on 2026-07-14 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleco_app', '0003_hallazgoriesgo_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Categoría de Pregunta',
                'verbose_name_plural': 'Categorías de Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('informe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='chaleco_app.informevisita')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chaleco_app.organizacion')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Pregunta / Requisito')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar de nuevas auditorías')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='chaleco_app.categoriapregunta')),
            ],
            options={
                'verbose_name': 'Pregunta de Auditoría',
                'verbose_name_plural': 'Preguntas de Auditoría',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('SI', 'SÍ'), ('NO', 'NO'), ('N/A', 'N/A')], default='N/A', max_length=3)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='chaleco_app.auditoria')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaleco_app.preguntaauditoria')),
            ],
            options={
                'unique_together': {('auditoria', 'pregunta')},
            },
        ),
    ]
