# Generated by Django 6.0.6 on 2026-07-14 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleco_app', '0004_categoriapregunta_auditoria_preguntaauditoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='informe',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='organizacion',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='cliente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='chaleco_app.clienteempresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
