# Generated by Django 6.0.6 on 2026-07-14 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaleco_app', '0005_remove_auditoria_informe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapregunta',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='preguntaauditoria',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='auditoria',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='resultado',
            field=models.CharField(choices=[('apto', 'Apto'), ('observaciones', 'Con Observaciones'), ('no_apto', 'No Apto'), ('en_progreso', 'En Progreso')], default='en_progreso', max_length=20),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='tipo',
            field=models.CharField(choices=[('express', 'Express (10 preguntas)'), ('completa', 'Completa (61 preguntas)')], default='completa', max_length=20),
        ),
        migrations.AddField(
            model_name='respuestaauditoria',
            name='pregunta_texto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='chaleco_app.clienteempresa'),
        ),
        migrations.AlterField(
            model_name='categoriapregunta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriapregunta',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preguntaauditoria',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='preguntaauditoria',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='respuestaauditoria',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chaleco_app.preguntaauditoria'),
        ),
    ]
